language: node_js

cache:
  directories:
    - node_modules
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn test

notifications:
  email:
    reciepients:
      - juan.gaviria@kommit.co
    on_success: always
    on_failure: always

deploy:
  provide: heroku
  skip-cleanup: true
  keep-history: true
  api_key: XXXX
  app: mr-store-backend
  on:
    repo: MRJUANGAVIRIA/platzi-store-backend
